---
- name: MariaDB -> Instalacion de MariaDB
  ansible.builtin.package:
    name: mariadb-server
    state: present

- name: MariaDB -> Arranque de MariaDB
  ansible.builtin.service:
    name: mariadb
    enabled: true
    state: started

- name: MariaDB -> Establecer contraseña para el usuario root en MariaDB
  shell: mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Pass1234';"
  ignore_errors: yes

- name: MariaDB -> Apertura del puerto 3306/tcp para la gestion de MariaDB
  ansible.posix.firewalld:
    port: 3306/tcp
    permanent: true
    state: enabled

- name: MariaDB -> Reinicio del Firewall para la apertura del puerto 3306/tcp de MariaDB
  ansible.builtin.command: firewall-cmd --reload

- name: Apache -> Instalacíon de Apache
  ansible.builtin.package:
    name: httpd
    state: present

- name: Apache -> Arranque de Apache
  ansible.builtin.service:
    name: httpd
    enabled: true
    state: started

- name: Apache -> Apertura del puerto 80/tcp para la exposicion de Apache
  ansible.posix.firewalld:
    port: 80/tcp
    permanent: true
    state: enabled

- name: Apache -> Reinicio del firewall para la apertura del puerto 80/tcp de Apache
  ansible.builtin.command: firewall-cmd --reload

- name: PHP -> Instalacion de PHP y librerias necesarias
  ansible.builtin.package:
    name:
      - php
      - php-mysqlnd

- name: PHP -> Reinicio del servicio Apache para integrar PHP
  ansible.builtin.service:
    name: httpd
    state: restarted
