---
- name: Docker -> Desinstalación de versiones antiguas de Docker
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop:
    - 'docker'
    - 'docker-ce'
    - 'docker-ce-cli'
    - 'docker-engine'
    - 'docker.io'
    - 'containerd.io'
    - 'runc'
    - 'docker-compose-plugin'
    - 'docker-compose'

- name: Docker -> Configuracion del repositorio docker -> Instalacion yum-utils
  ansible.builtin.package:
    name: yum-utils

- name: Docker -> Configuracion del repositorio docker -> Instalacion repositorio docker
  ansible.builtin.shell:
    cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Docker -> Instalacion de docker
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - 'docker-ce'
    - 'docker-ce-cli'
    - 'containerd.io'
    - 'docker-buildx-plugin'
    - 'docker-compose-plugin'

- name: Docker -> Arrancar docker
  ansible.builtin.service:
    name: docker
    enabled: yes
    state: started

- name: Docker -> Instalar Python3 para gestion docker en ansible
  ansible.builtin.package:
    name: python3
    state: present

- name: Docker -> Instalar librerias python
  ansible.builtin.pip:
    name: "{{ item }}"
    state: latest
  loop:
    - pip
    - docker
    - docker-compose
